"""Every surface a map may name, and the recording family it plays.

A map author writes "wet cobbles" and the client plays stone2step*.ogg. The
builder refuses a material that is not listed here, because the alternative is
a typo that silently becomes concrete on one map and nothing at all on another.

Only families that actually have a complete step/land/fall set in the pack are
used. The few that do not (bridge, rope, grasspacked) fall back at runtime.
"""

# name -> recording family
SURFACES = {
    # --- outdoor, hard ---------------------------------------------------
    "asphalt": "concrete2",
    "cracked asphalt": "concrete7",
    "new asphalt": "concrete4",
    "concrete pavement": "concrete5",
    "worn pavement": "concrete1",
    "paving slabs": "concrete3",
    "wet concrete": "wetconcrete",
    "cobbles": "stone1",
    "wet cobbles": "stone2",
    "flagstones": "stone",
    "granite setts": "stone1",
    "duracrete": "cement2",
    "plascrete": "cement",
    "screed": "cement1",
    # --- outdoor, loose --------------------------------------------------
    "gravel": "gravel1",
    "rail ballast": "gravel2",
    "loose scree": "gravel3",
    "shingle": "gravel",
    "packed dirt": "dirt2",
    "dry dirt": "dirt1",
    "cart track": "dirt3",
    "wet earth": "dirt4",
    "mud": "mud",
    "clay": "clay",
    "sand": "sand",
    "deep sand": "deepsand",
    "bare rock": "rocks1",
    "loose rock": "rocks",
    "boulders": "large_rock",
    "flint": "flint",
    # --- vegetation ------------------------------------------------------
    "grass": "grass3",
    "clipped lawn": "grass1",
    "dry grass": "grass2",
    "long grass": "long_grass",
    "meadow": "grass5",
    "weeds": "weed",
    "leaf litter": "leaves",
    "scrub": "brush",
    "dense scrub": "brush1",
    "fallen branches": "branch",
    # --- cold ------------------------------------------------------------
    "snow": "snow",
    "packed snow": "snow1",
    "ice": "ice",
    # --- water -----------------------------------------------------------
    "shallow water": "shallow",
    "tidal water": "water",
    "standing water": "water1",
    "open sea": "deepwater",
    "marsh": "marsh",
    "swamp": "swamp",
    # --- indoor, soft ----------------------------------------------------
    "carpet": "carpet1",
    "thin carpet": "carpet3",
    "office carpet": "carpet5",
    "worn carpet": "carpet2",
    "rug": "carpet4",
    "matting": "mat",
    # --- indoor, hard ----------------------------------------------------
    "ceramic tile": "tile1",
    "terrazzo": "tile2",
    "marble": "marble",
    "polished marble": "marble1",
    "linoleum": "linoleum",
    "concrete floor": "concrete5",
    "poured floor": "concrete9",
    "warehouse floor": "warehouse",
    "tunnel floor": "tunnel",
    "glass floor": "glass",
    "diamond plate": "diamond",
    # --- indoor, timber --------------------------------------------------
    "floorboards": "hardwood2",
    "bare boards": "plank",
    "parquet": "hardwood1",
    "plywood": "plywood",
    "timber decking": "deck",
    "ship deck": "deck",
    "old boards": "wood2",
    "creaking boards": "wood3",
    # --- metal -----------------------------------------------------------
    "steel plate": "metal4",
    "steel deck": "metal2",
    "hull plating": "metal1",
    "riveted steel": "metal6",
    "steel grating": "grate",
    "catwalk grating": "grate",
    "steel beam": "beam",
    # --- stairs and ramps ------------------------------------------------
    "concrete stairs": "stairs",
    "stone stairs": "stairs",
    "steel stairs": "metal3",
    "timber stairs": "wood3",
    "ramp surface": "concrete6",
    "steel ramp": "metal5",
    # --- climbs (the name is what makes them climbable) -------------------
    "access ladder": "ladder1",
    "maintenance rungs": "ladder2",
    "service ladder": "ladder",
    "cargo netting": "rope",
    "scaffold rungs": "fence",
    # --- seating and furniture surfaces used as terrain -------------------
    "bleacher seating": "bleacher",
    "bench seating": "chair",
    # --- walls (anything with "wall" in the name is walked into) ---------
    "brick wall": "wallbrick",
    "stone wall": "wallstone",
    "concrete wall": "wallstone",
    "duracrete wall": "wallstone",
    "rock wall": "wallrock",
    "cliff wall": "wallrock",
    "earth wall": "walldirt",
    "timber wall": "wallwood",
    "steel wall": "wallmetal",
    "hull wall": "wallmetal",
    "shutter wall": "wallmetal",
    "glass curtain wall": "wallglass",
    "window wall": "wallglass",
    "chainlink wall": "wallfence",
    "railing wall": "wallfence",
    "hedge wall": "wallgrass",
    "hoarding wall": "wallwood",
    "composite wall": "wallplastic",
    "curtained wall": "wallcarpet",
}

# Acoustic space kinds. The client stores the kind with the space; these are
# the vocabulary a map is allowed to use, so a typo cannot quietly become a
# different sort of room.
KINDS = {
    "room", "hall", "concourse", "atrium", "corridor", "stairwell", "cupboard",
    "office", "shop", "workshop", "warehouse", "hangar", "garage", "kitchen",
    "ward", "chapel", "vault", "cell", "cabin", "tunnel", "cave", "plant",
    "street", "alley", "square", "courtyard", "roof", "bridge", "platform",
    "open", "water", "shore", "forest", "mountain", "void",
}

# Looping ambience beds that exist in the pack, grouped by what they are for.
AMBIENCE = {
    "city day": "executioners_rage/environment/ambiance/city_day.wav",
    "city night": "executioners_rage/environment/ambiance/city_night.wav",
    "busy street": "executioners_rage/environment/ambiance/1st_street.wav",
    "quiet street": "executioners_rage/environment/ambiance/jasmine_street.wav",
    "side street": "executioners_rage/environment/ambiance/franklin.wav",
    "pavement": "executioners_rage/environment/ambiance/sidewalk_bank.wav",
    "back pavement": "executioners_rage/environment/ambiance/sidewalk_stoner.wav",
    "freeway": "executioners_rage/environment/ambiance/freeway.wav",
    "parkway": "executioners_rage/environment/ambiance/parkway.wav",
    "park": "executioners_rage/environment/ambiance/budleaf_park.wav",
    "grassland": "executioners_rage/environment/ambiance/grassy.wav",
    "open sky": "executioners_rage/environment/ambiance/blue_sky.wav",
    "car park": "executioners_rage/environment/ambiance/parking_lot_extra.wav",
    "station": "executioners_rage/environment/ambiance/train_station.wav",
    "warehouse": "executioners_rage/environment/ambiance/warehouse.wav",
    "scrapyard": "executioners_rage/environment/ambiance/bf_scrap_yard.wav",
    "bank hall": "executioners_rage/environment/ambiance/bank_atrium.wav",
    "bank counter": "executioners_rage/environment/ambiance/bank_counter.wav",
    "office": "executioners_rage/environment/ambiance/office.wav",
    "corridor": "executioners_rage/environment/ambiance/corridor.wav",
    "indoors": "executioners_rage/environment/ambiance/indoor.wav",
    "hospital": "executioners_rage/environment/ambiance/hospital.wav",
    "police station": "executioners_rage/environment/ambiance/police_station/default.wav",
    "armoury": "executioners_rage/environment/ambiance/police_station/armory.wav",
    "post office": "executioners_rage/environment/ambiance/post_office.wav",
    "shop": "executioners_rage/environment/ambiance/store1.wav",
    "small shop": "executioners_rage/environment/ambiance/store2.wav",
    "diner": "executioners_rage/environment/ambiance/eats.wav",
    "bar": "executioners_rage/environment/ambiance/whiskey_well.wav",
    "bar terrace": "executioners_rage/environment/ambiance/whiskey_well_patio.wav",
    "arcade": "executioners_rage/environment/ambiance/arcasino.wav",
    "house": "executioners_rage/environment/ambiance/house1.wav",
    "flat": "executioners_rage/environment/ambiance/house2.wav",
    "bathroom": "executioners_rage/environment/ambiance/bathroom.wav",
    "cave": "executioners_rage/environment/ambiance/cave.wav",
    "dead zone": "executioners_rage/environment/ambiance/dead_zone.wav",
    "fountain": "executioners_rage/environment/ambiance/fountain.wav",
    "forest": "executioners_rage/environment/ambiance/dark_forest.wav",
    "young forest": "executioners_rage/environment/ambiance/newbie_forest.wav",
    "rainforest": "executioners_rage/environment/ambiance/rainforest.wav",
    "birds": "executioners_rage/environment/ambiance/birds.wav",
    # root-level beds
    "ocean": "ocean.ogg",
    "surf": "ocean2.ogg",
    "heavy surf": "ocean3.ogg",
    "distant sea": "ocean4.ogg",
    "harbour water": "ocean_2.ogg",
    "river": "river.ogg",
    "waterfall": "waterfall.ogg",
    "small waterfall": "waterfall2.ogg",
    "rain": "rain.ogg",
    "heavy rain": "rain2.ogg",
    "cold wind": "cold_wind.ogg",
    "high wind": "cold_wind2.ogg",
    "gale": "hardwind1.ogg",
    "machinery hum": "hum.ogg",
    "city hum": "city1.ogg",
    "city birds": "citybirds.ogg",
    "woodland": "forest.ogg",
    "night": "night.ogg",
    "night woodland": "nighttime_forest.ogg",
    "desert day": "desertday.ogg",
    "desert night": "desertnight.ogg",
    "open air": "amb1.ogg",
    "high air": "amb2.ogg",
    "still air": "amb3.ogg",
}

# Destructible object presets available to maps (iwserver/content/object_presets.json).
PRESET_NAMES = {
    "bench", "table", "bookcase", "counter", "sofa", "bed", "locker", "cabinet",
    "display_case", "crate", "generator", "planter", "barrier", "workbench",
    "pew", "tank", "headstone", "screen",
}

# Interactive services. Each must have a sound directory under
# sounds/executioners_rage/environment/objects/.
FIXTURE_KINDS = {
    "atm", "vending_machine", "hospital_bed", "table", "kiosk", "computer1",
    "computer2", "post_box", "sink1", "sink2", "toilet1", "toilet2", "fridge",
    "coke_machine", "tv", "street_light", "sign", "dumpster", "crate",
    "parked_car1", "parked_car2", "parked_car3", "tree1", "tree2", "tree3",
    "tree4", "tree5", "wooden_planter", "well_speaker", "atrium_speaker",
    "security_radio1", "scrap_yard1", "scrap_yard2", "streams",
    "hospital_coagulator", "hospital_defibolator", "hospital_ventilator",
    "instrument_prep",
}
